/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DocumentSearch {
    }
}
declare global {
    interface HTMLDocumentSearchElement extends Components.DocumentSearch, HTMLStencilElement {
    }
    var HTMLDocumentSearchElement: {
        prototype: HTMLDocumentSearchElement;
        new (): HTMLDocumentSearchElement;
    };
    interface HTMLElementTagNameMap {
        "document-search": HTMLDocumentSearchElement;
    }
}
declare namespace LocalJSX {
    interface DocumentSearch {
    }
    interface IntrinsicElements {
        "document-search": DocumentSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "document-search": LocalJSX.DocumentSearch & JSXBase.HTMLAttributes<HTMLDocumentSearchElement>;
        }
    }
}
